config/routes.rb
Rails.application.routes.draw do
  match '/users', to: 'users#index', via: 'get'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :events
  resources :event_participatings, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
    has_many :event_participatings
    has_many :participants, through: :event_participatings, source: :user

    scope :past_events, -> { where("date <= ?", Time.now) }
    scope :upcoming_events, -> { where("date > ?", Time.now) }

    # def self.past_events
    #   self.where("date <= ?", Time.now)
    # end

    # def self.upcoming_events
    #   self.where("date > ?", Time.now)
    # end

    def past_event?
      self.date < Time.now
    end

end

app/models/event_participating.rb
class EventParticipating < ApplicationRecord
    belongs_to :event
    belongs_to :user

end

app/models/event_participiating.rb
class User < ApplicationRecord
    belongs_to :created_event, class_name: "Post"
    belongs_to :participant, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, inverse_of: :creator
  has_many :event_participatings
  has_many :participated_events, through: :event_participatings, source: :event

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_participatings_controller.rb
class EventParticipatingsController < ApplicationController

    def new
      @event_participating = EventParticipating.new
    end

    def edit

    end

    def create
      @event_participating = current_user.event_participatings.build(event_participatings_params)
      @event = Event.find(event_participatings_params[:event_id])
      respond_to do |format|
        if @event_participating.save
          format.html { redirect_to @event, notice: "You successfully joined this event!" }
          format.json { render :show, status: :created, location: @event }
        else
          flash.now[:warning] = 'There were problems when trying to create a new event registration'

          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @event_participating.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      # @event_participating = EventParticipating.find_by(user_id: user_id, event_id: event_id)
      @event_participating = EventParticipating.find(params[:id])
      @event = @event_participating.event
      @event_participating.destroy
      respond_to do |format|
        format.html { redirect_to @event, notice: "You successfully disenrolled!" }
        format.json { head :no_content }
      end
    end

    private

    def event_participatings_params
      params.require(:event_participating).permit(:user_id, :event_id)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @events = Event.all
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :place, :user_id, :content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %> 
      </ul>

  <div class="field">
    <div class="control">
      <%= f.input :name %>
      <%= f.input :date %>
      <%= f.input :place %>
      <%= f.input :content, input_html: { class: "textarea" },
                  wrapper: false, label_html: { class: "label" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title is-2">Events</h1>
    <div class="columns">
      <div class="column has-background-warning">
        <h3 class="title is-4">These are the past events:</h3>
        <% Event.past_events.each do |event| %>
          <div class="box">
            <article class="media">
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong><%= event.name %> </strong><br/>
                    <small>Date: <%= event.date %></small><br/>
                    <small>Place: <%= event.place %></small>
                    <br />
                    By: <%= event.creator.username %>
                  </p>
                </div>
                  <nav class="level is-mobile">
                    <div class="level-left">
                      <%= link_to event, class: "level-item" do %>
                        <span class="icon-text has-text-info">
                          <span class="icon"><i class="fas fa-eye"></i></span>
                          <span>Show</span>
                        </span>
                      <% end %>
                      <% if current_user == event.creator %>
                        <%= link_to edit_event_path(event), class: "level-item" do %>
                          <span class="icon-text has-text-info">
                            <span class="icon"><i class="fas fa-wrench"></i></span>
                            <span>Edit</span>
                          </span>
                        <% end %>
                        <%= link_to event, method: :delete, data: { confirm: "Are you sure?" }, class: "level-item" do %>
                          <span class="icon-text has-text-info">
                            <span class="icon"><i class="fas fa-trash"></i></span>
                            <span>Delete</span>
                          </span>
                        <% end %>
                      <% end %>
                    </div>
                  </nav>
              </div>
            </article>
          </div>
        <% end %>
      </div>
      <div class="column has-background-success">
        <h3 class="title is-4">These are the upcoming events:</h3>
        <% Event.upcoming_events.each do |event| %>
          <div class="box">
            <article class="media">
              <div class="media-content">
                <div class="content">
                  <p>
                    <strong><%= event.name %></strong><br/>
                    <small>Date: <%= event.date %></small><br/>
                    <small>Place: <%= event.place %></small>
                    <br />
                    By: <%= event.creator.username %>
                  </p>
                </div>
                  <nav class="level is-mobile">
                    <div class="level-left">
                      <%= link_to event, class: "level-item" do %>
                        <span class="icon-text has-text-info">
                          <span class="icon"><i class="fas fa-eye"></i></span>
                          <span>Show</span>
                        </span>
                      <% end %>
                      <% if current_user == event.creator %>
                        <%= link_to edit_event_path(event), class: "level-item" do %>
                          <span class="icon-text has-text-info">
                            <span class="icon"><i class="fas fa-wrench"></i></span>
                            <span>Edit</span>
                          </span>
                        <% end %>
                        <%= link_to event, method: :delete, data: { confirm: "Are you sure?" }, class: "level-item" do %>
                          <span class="icon-text has-text-info">
                            <span class="icon"><i class="fas fa-trash"></i></span>
                            <span>Delete</span>
                          </span>
                        <% end %>
                      <% end %>
                    </div>
                  </nav>
              </div>
            </article>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place %>
</p>
<p>
  <strong>Content:</strong>
  <%= @event.content %>
</p>

<p>
  <strong>Attend this event:</strong>
</p>
<% if user_signed_in? && current_user != @event.creator && !@event.past_event? %>
  <% unless @event.participants.where(id: current_user.id).exists? %>
    <%= form_with model: EventParticipating.new do |form| %>
      <%= form.hidden_field :event_id, value: @event.id %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <%= form.submit "Enroll", class: "button" %>
    <% end %>
  <% else %>
    <%# <%= form_with model: EventParticipating, method: :delete do |form| %>
      <%# <%= form.hidden_field :event_id, value: @event.id %>
      <%# <%= form.hidden_field :user_id, value: current_user.id %>
      <%# <%= form.submit "Disenroll", class: "button" %>
    <%# <% end %>
    <% @event.event_participatings.each do |e| %>
      <% if e.user_id == current_user.id %>
        <%= link_to "Disenroll", e, method: :delete, class: "button" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<div>
  <%# <% @events.each do |e| %>
    <% @event.participants.each do |p| %>
      <p><%= p.username %></p>
    <% end %>
  <%# <% end %> 
</div>

<hr />
<% if current_user == @event.creator %>
  <%= link_to 'Edit', edit_event_path(@event) %>
<% end %>
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/4dbb07b465.js" crossorigin="anonymous"></script>
  </head>

  <body>
    
     <% if flash[:notice] %>
        <div class="alert">
          <div class="notification is-primary global-notification">
            <p class="notice"><%= notice %></p>
          </div>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert">
          <div class="notifiaction is-primary global-notification">
            <p class="alert"><%= alert %></p>
          </div>
        </div>
      <% end %>

      <nav class="navbar is-light">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <h1 class="title is-3 has-text-link" >Private Events</h1>
          <% end %>
        </div>
        <div class="navbar-menu">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "Events", root_path, class: "button" %>
              </p>
              <p class="control">
                <%= link_to "Users", users_path, class:"button" %>
              </p>
            </div>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <% if user_signed_in? %>
                  <p class="control">
                    <%= link_to edit_user_registration_path, class: "button is-primary" do %>
                      <%= current_user.username %>
                    <% end %>
                  </p>
                  <p class="control">
                    <%= link_to "New Event", new_event_path, class:"button is-primary" %>
                  </p>
                  <p class="control">
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-danger" %>
                  </p>
                <% else %>
                  <p class="control">
                    <%= link_to "Sign In", new_user_session_path, class:"button is-light" %>
                  </p>
                  <p class="control">
                    <%= link_to "Sign Up", new_user_registration_path, class:"button is-primary" %>
                  </p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </nav>

    <%= yield %>
    <footer class="footer">
        <div class="content has-text-centered">
          <p>
            This website was made by <%= link_to "Kamilov-glitch", "https://github.com/Kamilov-glitch", target: "_blank" %>
          </p>
        </div>
      </footer>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
  <%= user.name %>
  <%= user.username %>
  <% user.participated_events.each do |e| %>
    <% if e.date < Time.now %>
      <p>This event(s) occured in past:</p>
      <%= e.name %><br/>
    <% else %>
      <p>Upcoming events</p>
      <%= e.name %><br/>
    <% end %>
  <% end %>
  <hr />
<% end %>